Page({
  data:{
    nodes:[{
      name:'div',
      attrs:{
        class:'div_class',
        style:'line-height:60px;color:red;'
      },
      children:[{
        type:'text',
        text:'Hello!'
      }]
    }]
  },
  tap:function(){
    console.log('tap')
  }
})